import type { ProblemContent } from "@/lib/schemas/12-pitch-deck";

interface Props {
  title: string;
  subtitle: string | null;
  content: ProblemContent;
}

export default function ProblemSlide({ title, subtitle, content }: Props) {
  return (
    <div className="slide-inner">
      <div className="slide-accent-bar" />
      <div className="slide-body">
        <h2 className="slide-title">{title}</h2>
        {subtitle && <p className="slide-subtitle">{subtitle}</p>}
        <p style={{ fontSize: "clamp(13px,1.8vw,18px)", fontWeight: 700, color: "#111827", marginBottom: 12, lineHeight: 1.3 }}>
          {content.problem_statement}
        </p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 10, marginBottom: 12 }}>
          {content.pain_points.map((pp, i) => (
            <div key={i} style={{ background: "#F3F4F6", borderRadius: 8, padding: "10px 10px 10px", border: "1px solid #E5E7EB" }}>
              <div style={{ fontSize: "clamp(10px,1.4vw,14px)", color: "#9CA3AF", marginBottom: 2 }}>{pp.icon_suggestion}</div>
              <div style={{ fontSize: "clamp(10px,1.4vw,13px)", fontWeight: 700, color: "#111827", marginBottom: 3 }}>{pp.heading}</div>
              <div style={{ fontSize: "clamp(9px,1.2vw,11px)", color: "#6B7280", lineHeight: 1.4 }}>{pp.description}</div>
            </div>
          ))}
        </div>
        <p style={{ fontSize: "clamp(9px,1.2vw,11px)", color: "#6B7280", fontStyle: "italic" }}>Who feels this: {content.who_feels_this}</p>
      </div>
      <SlideFooter num={1} />
    </div>
  );
}

export function SlideFooter({ num }: { num: number }) {
  return (
    <div style={{ position: "absolute", bottom: "3%", left: "3%", right: "3%", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
      <span style={{ fontSize: "clamp(7px,1vw,9px)", color: "#D1D5DB" }}>Generated by MarketMind AI · marketmind.ai</span>
      <span style={{ fontSize: "clamp(7px,1vw,9px)", color: "#9CA3AF" }}>{num}</span>
    </div>
  );
}
