"use client";

import type PptxGenJS from "pptxgenjs";
import type {
  PitchDeckOutput,
  Slide,
  ProblemContent,
  SolutionContent,
  MarketSizeContent,
  CustomerContent,
  CompetitorContent,
  BusinessModelContent,
  GoToMarketContent,
  RiskContent,
  WhyNowContent,
  AskContent,
} from "@/lib/schemas/12-pitch-deck";

type PptxSlide = PptxGenJS.Slide;
type PptxInstance = PptxGenJS;

const SAFFRON = "FF9933";
const DARK = "111827";
const GRAY = "6B7280";
const LIGHT_GRAY = "F3F4F6";
const BLUE = "1A56DB";
const GREEN = "10B981";
const RED = "EF4444";
const ORANGE = "F59E0B";
const WHITE = "FFFFFF";

function addMasterElements(
  slide: PptxSlide,
  slideNum: number
) {
  // Left accent bar
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0, y: 0, w: 0.08, h: 5.625,
    fill: { color: SAFFRON },
    line: { width: 0 },
  });

  // Footer
  slide.addText("Generated by MarketMind AI  ·  marketmind.ai", {
    x: 3, y: 5.28, w: 4, h: 0.22,
    fontSize: 8, color: "D1D5DB", align: "center",
  });

  // Slide number
  slide.addText(String(slideNum), {
    x: 9.3, y: 5.28, w: 0.5, h: 0.22,
    fontSize: 9, color: "9CA3AF", align: "right",
  });
}

function addSlideTitle(
  slide: PptxSlide,
  title: string,
  subtitle: string | null
) {
  slide.addText(title, {
    x: 0.3, y: 0.18, w: 9.4, h: 0.5,
    fontSize: 28, bold: true, color: DARK, fontFace: "Arial",
  });
  if (subtitle) {
    slide.addText(subtitle, {
      x: 0.3, y: 0.68, w: 9.4, h: 0.3,
      fontSize: 14, color: GRAY, fontFace: "Arial",
    });
  }
}

function renderProblemSlide(
  pptx: PptxInstance,
  data: Slide
) {
  const slide = pptx.addSlide();
  slide.background = { color: WHITE };
  addMasterElements(slide, data.slide_number);
  addSlideTitle(slide, data.title, data.subtitle);

  const c = data.content as ProblemContent;
  slide.addText(c.problem_statement, {
    x: 0.3, y: 1.1, w: 9.4, h: 0.7,
    fontSize: 20, bold: true, color: DARK, fontFace: "Arial", wrap: true,
  });

  const boxW = 2.9;
  const boxH = 1.5;
  const startX = 0.3;
  const startY = 1.9;
  const gap = 0.25;

  c.pain_points.forEach((pp, i) => {
    const x = startX + i * (boxW + gap);
    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x, y: startY, w: boxW, h: boxH,
      fill: { color: LIGHT_GRAY },
      line: { color: "E5E7EB", width: 1 },
      rectRadius: 0.1,
    });
    slide.addText(pp.icon_suggestion, {
      x, y: startY + 0.1, w: boxW, h: 0.3,
      fontSize: 11, color: "9CA3AF", align: "center",
    });
    slide.addText(pp.heading, {
      x: x + 0.1, y: startY + 0.38, w: boxW - 0.2, h: 0.35,
      fontSize: 13, bold: true, color: DARK, align: "center",
    });
    slide.addText(pp.description, {
      x: x + 0.1, y: startY + 0.72, w: boxW - 0.2, h: 0.65,
      fontSize: 10, color: GRAY, align: "center", wrap: true,
    });
  });

  slide.addText(`Who feels this: ${c.who_feels_this}`, {
    x: 0.3, y: 3.55, w: 9.4, h: 0.3,
    fontSize: 11, color: GRAY, italic: true,
  });
}

function renderSolutionSlide(
  pptx: PptxInstance,
  data: Slide
) {
  const slide = pptx.addSlide();
  slide.background = { color: WHITE };
  addMasterElements(slide, data.slide_number);
  addSlideTitle(slide, data.title, data.subtitle);

  const c = data.content as SolutionContent;
  const colY = 1.1;
  const colH = 2.5;

  // BEFORE column
  slide.addText("Before ✗", {
    x: 0.3, y: colY, w: 4.2, h: 0.4,
    fontSize: 14, bold: true, color: RED,
  });
  c.before.forEach((b, i) => {
    slide.addText(`✗  ${b}`, {
      x: 0.3, y: colY + 0.45 + i * 0.4, w: 4.2, h: 0.38,
      fontSize: 12, color: RED, wrap: true,
    });
  });

  // Divider arrow
  slide.addText("→", {
    x: 4.65, y: colY + 0.9, w: 0.6, h: 0.5,
    fontSize: 24, color: GRAY, align: "center",
  });

  // AFTER column
  slide.addText("After ✓", {
    x: 5.4, y: colY, w: 4.2, h: 0.4,
    fontSize: 14, bold: true, color: GREEN,
  });
  c.after.forEach((a, i) => {
    slide.addText(`✓  ${a}`, {
      x: 5.4, y: colY + 0.45 + i * 0.4, w: 4.2, h: 0.38,
      fontSize: 12, color: GREEN, wrap: true,
    });
  });

  // Key differentiator banner
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0.3, y: colY + colH, w: 9.4, h: 0.55,
    fill: { color: SAFFRON },
    line: { width: 0 },
  });
  slide.addText(`⭐  ${c.key_differentiator}`, {
    x: 0.4, y: colY + colH + 0.05, w: 9.2, h: 0.45,
    fontSize: 13, bold: true, color: DARK, align: "center",
  });
}

function renderMarketSizeSlide(
  pptx: PptxInstance,
  data: Slide
) {
  const slide = pptx.addSlide();
  slide.background = { color: WHITE };
  addMasterElements(slide, data.slide_number);
  addSlideTitle(slide, data.title, data.subtitle);

  const c = data.content as MarketSizeContent;

  // Growth rate badge
  slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
    x: 7.8, y: 0.18, w: 1.8, h: 0.38,
    fill: { color: "D1FAE5" },
    line: { color: GREEN, width: 1 },
    rectRadius: 0.08,
  });
  slide.addText(`📈 ${c.growth_rate}`, {
    x: 7.85, y: 0.22, w: 1.7, h: 0.3,
    fontSize: 11, bold: true, color: "065F46", align: "center",
  });

  const boxes = [
    { label: "TAM — Total Market", value: c.tam_inr, sub: c.tam_usd, bg: BLUE, fg: WHITE, x: 0.3, w: 4.5 },
    { label: "SAM — Serviceable Market", value: c.sam_inr, sub: "", bg: "3B82F6", fg: WHITE, x: 4.95, w: 2.4 },
    { label: "SOM — Your Target", value: c.som_inr, sub: "", bg: "BFDBFE", fg: DARK, x: 7.5, w: 2.1 },
  ];

  boxes.forEach((box) => {
    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x: box.x, y: 1.1, w: box.w, h: 2.4,
      fill: { color: box.bg },
      line: { width: 0 },
      rectRadius: 0.12,
    });
    slide.addText(box.label, {
      x: box.x + 0.1, y: 1.2, w: box.w - 0.2, h: 0.35,
      fontSize: 10, color: box.fg, align: "center", bold: true,
    });
    slide.addText(box.value, {
      x: box.x + 0.05, y: 1.6, w: box.w - 0.1, h: 0.8,
      fontSize: box.w > 3 ? 22 : 16, bold: true, color: box.fg, align: "center", wrap: true,
    });
    if (box.sub) {
      slide.addText(box.sub, {
        x: box.x + 0.1, y: 2.45, w: box.w - 0.2, h: 0.3,
        fontSize: 11, color: "BFDBFE", align: "center",
      });
    }
  });

  slide.addText(c.why_now_one_line, {
    x: 0.3, y: 3.65, w: 9.4, h: 0.35,
    fontSize: 12, color: GRAY, italic: true, align: "center",
  });
  slide.addText(`Source: ${c.source}`, {
    x: 0.3, y: 4.05, w: 9.4, h: 0.25,
    fontSize: 9, color: "9CA3AF", align: "center",
  });
}

function renderCustomerSlide(
  pptx: PptxInstance,
  data: Slide
) {
  const slide = pptx.addSlide();
  slide.background = { color: WHITE };
  addMasterElements(slide, data.slide_number);
  addSlideTitle(slide, data.title, data.subtitle);

  const c = data.content as CustomerContent;

  c.personas.forEach((p, i) => {
    const x = 0.3 + i * 4.85;
    const w = 4.55;
    const y = 1.1;
    const h = 3.0;

    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x, y, w, h,
      fill: { color: LIGHT_GRAY },
      line: { color: "E5E7EB", width: 1 },
      rectRadius: 0.12,
    });

    // Header
    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x, y, w, h: 0.5,
      fill: { color: DARK },
      line: { width: 0 },
      rectRadius: 0.12,
    });
    slide.addText(`${p.name}  ·  ${p.age_range}`, {
      x: x + 0.15, y: y + 0.08, w: w - 0.3, h: 0.35,
      fontSize: 13, bold: true, color: WHITE,
    });

    // Tier city badge
    const isTier2or3 = p.tier_city.includes("2") || p.tier_city.includes("3");
    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x: x + 0.15, y: y + 0.62, w: 1.5, h: 0.28,
      fill: { color: isTier2or3 ? SAFFRON : BLUE },
      line: { width: 0 },
      rectRadius: 0.06,
    });
    slide.addText(p.tier_city, {
      x: x + 0.15, y: y + 0.63, w: 1.5, h: 0.26,
      fontSize: 9, bold: true, color: WHITE, align: "center",
    });

    // Income
    slide.addText(p.income_inr, {
      x: x + 1.8, y: y + 0.62, w: w - 2.0, h: 0.28,
      fontSize: 11, color: GREEN, bold: true,
    });

    slide.addText("Job to be done:", {
      x: x + 0.15, y: y + 1.05, w: w - 0.3, h: 0.25,
      fontSize: 9, bold: true, color: GRAY,
    });
    slide.addText(p.job_to_be_done, {
      x: x + 0.15, y: y + 1.28, w: w - 0.3, h: 0.45,
      fontSize: 11, color: DARK, wrap: true,
    });

    slide.addText("Biggest frustration:", {
      x: x + 0.15, y: y + 1.82, w: w - 0.3, h: 0.25,
      fontSize: 9, bold: true, color: RED,
    });
    slide.addText(p.biggest_frustration, {
      x: x + 0.15, y: y + 2.05, w: w - 0.3, h: 0.45,
      fontSize: 11, color: DARK, wrap: true,
    });
  });
}

function renderCompetitorSlide(
  pptx: PptxInstance,
  data: Slide
) {
  const slide = pptx.addSlide();
  slide.background = { color: WHITE };
  addMasterElements(slide, data.slide_number);
  addSlideTitle(slide, data.title, data.subtitle);

  const c = data.content as CompetitorContent;

  // Position statement
  slide.addText(c.our_position, {
    x: 0.3, y: 0.95, w: 9.4, h: 0.32,
    fontSize: 13, color: BLUE, italic: true, bold: true,
  });

  // Table header
  const tableTop = 1.35;
  const colWidths = [2.4, 2.6, 2.6, 1.6];
  const headers = ["Competitor", "Strength", "Weakness", "Threat"];
  let curX = 0.3;
  colWidths.forEach((cw, i) => {
    slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
      x: curX, y: tableTop, w: cw, h: 0.35,
      fill: { color: DARK },
      line: { width: 0 },
    });
    slide.addText(headers[i], {
      x: curX + 0.08, y: tableTop + 0.05, w: cw - 0.1, h: 0.25,
      fontSize: 10, bold: true, color: WHITE,
    });
    curX += cw + 0.03;
  });

  // Table rows
  c.competitors.forEach((comp, rowIdx) => {
    const rowY = tableTop + 0.38 + rowIdx * 0.4;
    const rowBg = rowIdx % 2 === 0 ? WHITE : LIGHT_GRAY;
    const threatColor = comp.threat_level === "high" ? RED : comp.threat_level === "medium" ? ORANGE : GREEN;
    const cells = [comp.name, comp.their_strength, comp.their_weakness, comp.threat_level.toUpperCase()];
    const cellColors = [DARK, GRAY, GRAY, WHITE];
    const cellBgs = [rowBg, rowBg, rowBg, threatColor];
    let cx = 0.3;
    colWidths.forEach((cw, ci) => {
      slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
        x: cx, y: rowY, w: cw, h: 0.38,
        fill: { color: cellBgs[ci] },
        line: { color: "E5E7EB", width: 1 },
      });
      slide.addText(cells[ci], {
        x: cx + 0.08, y: rowY + 0.06, w: cw - 0.12, h: 0.28,
        fontSize: 10, color: cellColors[ci], bold: ci === 0,
      });
      cx += cw + 0.03;
    });
  });

  // Advantage banner
  const bannerY = tableTop + 0.38 + c.competitors.length * 0.4 + 0.1;
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0.3, y: bannerY, w: 9.4, h: 0.5,
    fill: { color: SAFFRON },
    line: { width: 0 },
  });
  slide.addText(`Our advantage: ${c.our_advantage}`, {
    x: 0.4, y: bannerY + 0.08, w: 9.2, h: 0.35,
    fontSize: 12, bold: true, color: DARK, align: "center",
  });
}

function renderBusinessModelSlide(
  pptx: PptxInstance,
  data: Slide
) {
  const slide = pptx.addSlide();
  slide.background = { color: WHITE };
  addMasterElements(slide, data.slide_number);
  addSlideTitle(slide, data.title, data.subtitle);

  const c = data.content as BusinessModelContent;
  const cardW = (9.4 - (c.revenue_streams.length - 1) * 0.2) / c.revenue_streams.length;

  c.revenue_streams.forEach((rs, i) => {
    const x = 0.3 + i * (cardW + 0.2);
    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x, y: 1.0, w: cardW, h: 2.0,
      fill: { color: LIGHT_GRAY },
      line: { color: "E5E7EB", width: 1 },
      rectRadius: 0.12,
    });
    slide.addText(rs.name, {
      x: x + 0.1, y: 1.1, w: cardW - 0.2, h: 0.4,
      fontSize: 14, bold: true, color: DARK, wrap: true,
    });
    slide.addText(rs.how_it_works, {
      x: x + 0.1, y: 1.55, w: cardW - 0.2, h: 0.5,
      fontSize: 11, color: GRAY, wrap: true,
    });
    slide.addText(rs.example, {
      x: x + 0.1, y: 2.1, w: cardW - 0.2, h: 0.4,
      fontSize: 18, bold: true, color: SAFFRON,
    });
  });

  slide.addText(c.unit_economics_headline, {
    x: 0.3, y: 3.15, w: 9.4, h: 0.45,
    fontSize: 20, bold: true, color: GREEN, align: "center",
  });
  slide.addText(c.path_to_profitability, {
    x: 0.3, y: 3.65, w: 9.4, h: 0.3,
    fontSize: 12, color: GRAY, italic: true, align: "center",
  });
}

function renderGoToMarketSlide(
  pptx: PptxInstance,
  data: Slide
) {
  const slide = pptx.addSlide();
  slide.background = { color: WHITE };
  addMasterElements(slide, data.slide_number);
  addSlideTitle(slide, data.title, data.subtitle);

  const c = data.content as GoToMarketContent;
  const colW = 3.0;
  const colBgs = [WHITE, LIGHT_GRAY, WHITE];
  const startY = 1.0;
  const colH = 2.9;

  c.phases.forEach((phase, i) => {
    const x = 0.3 + i * (colW + 0.2);
    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x, y: startY, w: colW, h: colH,
      fill: { color: colBgs[i] },
      line: { color: "E5E7EB", width: 1 },
      rectRadius: 0.1,
    });
    slide.addText(phase.phase, {
      x: x + 0.1, y: startY + 0.1, w: colW - 0.2, h: 0.28,
      fontSize: 10, bold: true, color: SAFFRON,
    });
    slide.addText(phase.focus, {
      x: x + 0.1, y: startY + 0.38, w: colW - 0.2, h: 0.42,
      fontSize: 12, bold: true, color: DARK, wrap: true,
    });
    phase.key_actions.forEach((action, ai) => {
      slide.addText(`• ${action}`, {
        x: x + 0.1, y: startY + 0.85 + ai * 0.38, w: colW - 0.2, h: 0.36,
        fontSize: 10, color: GRAY, wrap: true,
      });
    });

    // Milestone badge
    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x: x + 0.1, y: startY + colH - 0.48, w: colW - 0.2, h: 0.38,
      fill: { color: GREEN },
      line: { width: 0 },
      rectRadius: 0.06,
    });
    slide.addText(phase.target_milestone, {
      x: x + 0.1, y: startY + colH - 0.44, w: colW - 0.2, h: 0.3,
      fontSize: 9, bold: true, color: WHITE, align: "center", wrap: true,
    });
  });

  // First customer channel
  slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
    x: 0.3, y: startY + colH + 0.12, w: 9.4, h: 0.42,
    fill: { color: "EFF6FF" },
    line: { color: BLUE, width: 1 },
    rectRadius: 0.08,
  });
  slide.addText(`First customer channel: ${c.first_customer_channel}`, {
    x: 0.45, y: startY + colH + 0.17, w: 9.1, h: 0.32,
    fontSize: 11, bold: true, color: BLUE,
  });
}

function renderRiskSlide(
  pptx: PptxInstance,
  data: Slide
) {
  const slide = pptx.addSlide();
  slide.background = { color: WHITE };
  addMasterElements(slide, data.slide_number);
  addSlideTitle(slide, data.title, data.subtitle);

  const c = data.content as RiskContent;
  const tableTop = 1.0;
  const colWidths = [3.2, 1.4, 4.6];
  const headers = ["Risk", "Severity", "Mitigation"];

  let curX = 0.3;
  colWidths.forEach((cw, i) => {
    slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
      x: curX, y: tableTop, w: cw, h: 0.35,
      fill: { color: DARK },
      line: { width: 0 },
    });
    slide.addText(headers[i], {
      x: curX + 0.08, y: tableTop + 0.05, w: cw - 0.1, h: 0.25,
      fontSize: 10, bold: true, color: WHITE,
    });
    curX += cw + 0.04;
  });

  c.risks.forEach((risk, rowIdx) => {
    const rowY = tableTop + 0.38 + rowIdx * 0.48;
    const rowBg = rowIdx % 2 === 0 ? WHITE : LIGHT_GRAY;
    const sevColor = risk.severity === "high" ? RED : risk.severity === "medium" ? ORANGE : GREEN;
    let cx = 0.3;
    [
      { text: risk.risk, color: DARK, bg: rowBg, bold: true },
      { text: risk.severity.toUpperCase(), color: WHITE, bg: sevColor, bold: true },
      { text: risk.mitigation, color: GRAY, bg: rowBg, bold: false },
    ].forEach((cell, ci) => {
      slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
        x: cx, y: rowY, w: colWidths[ci], h: 0.46,
        fill: { color: cell.bg },
        line: { color: "E5E7EB", width: 1 },
      });
      slide.addText(cell.text, {
        x: cx + 0.08, y: rowY + 0.08, w: colWidths[ci] - 0.12, h: 0.32,
        fontSize: 10, color: cell.color, bold: cell.bold, wrap: true,
      });
      cx += colWidths[ci] + 0.04;
    });
  });

  // Honest acknowledgment
  const ackY = tableTop + 0.38 + c.risks.length * 0.48 + 0.15;
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0.3, y: ackY, w: 0.06, h: 0.52,
    fill: { color: BLUE },
    line: { width: 0 },
  });
  slide.addText(c.biggest_risk_acknowledged, {
    x: 0.5, y: ackY + 0.05, w: 9.1, h: 0.42,
    fontSize: 11, color: GRAY, italic: true, wrap: true,
  });
}

function renderWhyNowSlide(
  pptx: PptxInstance,
  data: Slide
) {
  const slide = pptx.addSlide();
  slide.background = { color: WHITE };
  addMasterElements(slide, data.slide_number);
  addSlideTitle(slide, data.title, data.subtitle);

  const c = data.content as WhyNowContent;
  const cardW = 2.9;
  const cardH = 2.5;

  c.tailwinds.forEach((tw, i) => {
    const x = 0.3 + i * (cardW + 0.25);
    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x, y: 1.0, w: cardW, h: cardH,
      fill: { color: LIGHT_GRAY },
      line: { color: "E5E7EB", width: 1 },
      rectRadius: 0.12,
    });
    slide.addText(tw.trend, {
      x: x + 0.12, y: 1.1, w: cardW - 0.24, h: 0.52,
      fontSize: 14, bold: true, color: DARK, wrap: true,
    });
    slide.addText(tw.evidence, {
      x: x + 0.12, y: 1.68, w: cardW - 0.24, h: 0.65,
      fontSize: 10, color: GRAY, italic: true, wrap: true,
    });
    slide.addText(tw.impact_on_us, {
      x: x + 0.12, y: 2.42, w: cardW - 0.24, h: 0.48,
      fontSize: 11, bold: true, color: SAFFRON, wrap: true,
    });
  });

  // Inflection point banner
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0.3, y: 3.65, w: 9.4, h: 0.52,
    fill: { color: DARK },
    line: { width: 0 },
  });
  slide.addText(`⚡  ${c.inflection_point}`, {
    x: 0.4, y: 3.72, w: 9.2, h: 0.38,
    fontSize: 13, bold: true, color: WHITE, align: "center",
  });
}

function renderAskSlide(
  pptx: PptxInstance,
  data: Slide
) {
  const slide = pptx.addSlide();
  slide.background = { color: WHITE };
  addMasterElements(slide, data.slide_number);
  addSlideTitle(slide, data.title, data.subtitle);

  const c = data.content as AskContent;

  if (c.mode === "funding_ask" && c.amount_inr) {
    slide.addText(c.amount_inr, {
      x: 0.3, y: 1.0, w: 9.4, h: 0.9,
      fontSize: 48, bold: true, color: BLUE, align: "center",
    });
    if (c.runway_months) {
      slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
        x: 3.5, y: 1.95, w: 3.0, h: 0.38,
        fill: { color: "D1FAE5" },
        line: { color: GREEN, width: 1 },
        rectRadius: 0.08,
      });
      slide.addText(`${c.runway_months} months runway`, {
        x: 3.5, y: 1.98, w: 3.0, h: 0.32,
        fontSize: 12, bold: true, color: "065F46", align: "center",
      });
    }
    const dotColors = [BLUE, SAFFRON, GREEN, "8B5CF6"];
    (c.use_of_funds ?? []).forEach((use, i) => {
      slide.addShape("ellipse" as Parameters<typeof slide.addShape>[0], {
        x: 0.5, y: 2.5 + i * 0.42, w: 0.18, h: 0.18,
        fill: { color: dotColors[i % dotColors.length] },
        line: { width: 0 },
      });
      slide.addText(use, {
        x: 0.78, y: 2.45 + i * 0.42, w: 8.8, h: 0.38,
        fontSize: 12, color: DARK, wrap: true,
      });
    });
  } else {
    // Next steps mode
    (c.next_steps ?? []).slice(0, 4).forEach((step, i) => {
      const x = i % 2 === 0 ? 0.3 : 5.1;
      const y = i < 2 ? 1.0 : 2.5;
      slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
        x, y, w: 4.5, h: 1.3,
        fill: { color: LIGHT_GRAY },
        line: { color: "E5E7EB", width: 1 },
        rectRadius: 0.1,
      });
      slide.addText(String(i + 1), {
        x: x + 0.15, y: y + 0.15, w: 0.5, h: 0.6,
        fontSize: 32, bold: true, color: SAFFRON,
      });
      slide.addText(step, {
        x: x + 0.7, y: y + 0.25, w: 3.65, h: 0.75,
        fontSize: 12, color: DARK, wrap: true,
      });
    });
  }

  // Contact
  slide.addText(c.contact_prompt, {
    x: 0.3, y: 4.5, w: 9.4, h: 0.3,
    fontSize: 13, bold: true, color: DARK, align: "center",
  });
  slide.addText(c.closing_statement, {
    x: 0.3, y: 4.82, w: 9.4, h: 0.3,
    fontSize: 12, color: GRAY, italic: true, align: "center",
  });
}

export async function generatePPTX(deckData: PitchDeckOutput): Promise<Blob> {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";

  const renderers: Record<string, (pptx: PptxInstance, slide: Slide) => void> = {
    problem: renderProblemSlide,
    solution: renderSolutionSlide,
    market_size: renderMarketSizeSlide,
    customer: renderCustomerSlide,
    competitor: renderCompetitorSlide,
    business_model: renderBusinessModelSlide,
    go_to_market: renderGoToMarketSlide,
    risk: renderRiskSlide,
    why_now: renderWhyNowSlide,
    ask: renderAskSlide,
  };

  for (const slide of deckData.slides) {
    const renderer = renderers[slide.slide_type];
    if (renderer) renderer(pptx, slide);
  }

  const blob = await pptx.write({ outputType: "blob" }) as unknown as Blob;
  return blob;
}
