"use client";

import type PptxGenJS from "pptxgenjs";
import type {
  PitchDeckOutput,
  Slide,
  ProblemContent,
  SolutionContent,
  MarketSizeContent,
  CustomerContent,
  CompetitorContent,
  BusinessModelContent,
  GoToMarketContent,
  RiskContent,
  WhyNowContent,
  AskContent,
} from "@/lib/schemas/12-pitch-deck";

type PptxSlide = PptxGenJS.Slide;
type PptxInstance = PptxGenJS;

// ── BRAND PALETTE ──────────────────────────────────────────────────────────────
const C = {
  ink:       "0F172A",  // near-black
  saffron:   "F97316",  // orange-500
  safLight:  "FFF7ED",  // orange-50
  blue:      "2563EB",  // blue-600
  blueLight: "EFF6FF",  // blue-50
  blueMid:   "BFDBFE",  // blue-200
  green:     "16A34A",  // green-600
  greenLight:"F0FDF4",  // green-50
  red:       "DC2626",  // red-600
  amber:     "D97706",  // amber-600
  slate2:    "E2E8F0",  // slate-200
  slate3:    "CBD5E1",  // slate-300
  slate5:    "64748B",  // slate-500
  slate6:    "475569",  // slate-600
  slate8:    "1E293B",  // slate-800
  white:     "FFFFFF",
  offwhite:  "F8FAFC",  // slate-50
  card:      "F1F5F9",  // slate-100
};

// ── HELPERS ────────────────────────────────────────────────────────────────────

function addHeaderBand(slide: PptxSlide, title: string, subtitle: string | null, slideNum: number, accentColor = C.saffron) {
  // Dark header band
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0, y: 0, w: 10, h: 1.35,
    fill: { color: C.ink },
    line: { width: 0 },
  });
  // Accent stripe bottom of header
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0, y: 1.3, w: 10, h: 0.07,
    fill: { color: accentColor },
    line: { width: 0 },
  });
  // Slide number pill top-right
  slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
    x: 9.0, y: 0.15, w: 0.7, h: 0.38,
    fill: { color: accentColor },
    line: { width: 0 },
    rectRadius: 0.08,
  });
  slide.addText(String(slideNum).padStart(2, "0"), {
    x: 9.0, y: 0.18, w: 0.7, h: 0.32,
    fontSize: 12, bold: true, color: C.white, align: "center", fontFace: "Arial",
  });
  // Title
  slide.addText(title, {
    x: 0.35, y: 0.12, w: 8.5, h: 0.58,
    fontSize: 26, bold: true, color: C.white, fontFace: "Arial",
  });
  // Subtitle
  if (subtitle) {
    slide.addText(subtitle, {
      x: 0.35, y: 0.72, w: 8.5, h: 0.32,
      fontSize: 12, color: accentColor, fontFace: "Arial", italic: true,
    });
  }
}

function addFooter(slide: PptxSlide) {
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0, y: 5.45, w: 10, h: 0.18,
    fill: { color: C.card },
    line: { width: 0 },
  });
  slide.addText("Generated by MarketMind AI  ·  marketmind.ai", {
    x: 0.3, y: 5.45, w: 9.4, h: 0.18,
    fontSize: 7, color: C.slate5, align: "center", fontFace: "Arial",
  });
}

function roundRect(
  slide: PptxSlide,
  x: number, y: number, w: number, h: number,
  fillColor: string, borderColor?: string, radius = 0.1
) {
  slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
    x, y, w, h,
    fill: { color: fillColor },
    line: borderColor ? { color: borderColor, width: 1 } : { width: 0 },
    rectRadius: radius,
  });
}

function badge(slide: PptxSlide, text: string, x: number, y: number, w: number, bg: string, fg: string) {
  roundRect(slide, x, y, w, 0.3, bg, undefined, 0.06);
  slide.addText(text, {
    x, y: y + 0.03, w, h: 0.24,
    fontSize: 9, bold: true, color: fg, align: "center", fontFace: "Arial",
  });
}

// ── SLIDE RENDERERS ────────────────────────────────────────────────────────────

function renderProblemSlide(pptx: PptxInstance, data: Slide) {
  const slide = pptx.addSlide();
  slide.background = { color: C.offwhite };
  addHeaderBand(slide, data.title, data.subtitle, data.slide_number, C.saffron);
  addFooter(slide);

  const c = data.content as ProblemContent;

  // Large problem statement
  roundRect(slide, 0.3, 1.5, 9.4, 0.7, C.safLight, C.saffron, 0.08);
  slide.addText(c.problem_statement, {
    x: 0.5, y: 1.55, w: 9.1, h: 0.6,
    fontSize: 16, bold: true, color: C.ink, fontFace: "Arial", wrap: true,
  });

  // 3 pain point cards
  const boxW = 2.95;
  const gap = 0.175;
  c.pain_points.forEach((pp, i) => {
    const x = 0.3 + i * (boxW + gap);
    roundRect(slide, x, 2.35, boxW, 2.05, C.white, C.slate2, 0.12);
    // Top accent
    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x, y: 2.35, w: boxW, h: 0.08,
      fill: { color: C.saffron },
      line: { width: 0 },
      rectRadius: 0.1,
    });
    // Icon
    slide.addText(pp.icon_suggestion, {
      x: x + 0.15, y: 2.52, w: boxW - 0.3, h: 0.42,
      fontSize: 22, align: "center",
    });
    slide.addText(pp.heading, {
      x: x + 0.1, y: 2.96, w: boxW - 0.2, h: 0.38,
      fontSize: 12, bold: true, color: C.ink, align: "center", fontFace: "Arial",
    });
    slide.addText(pp.description, {
      x: x + 0.1, y: 3.37, w: boxW - 0.2, h: 0.8,
      fontSize: 10, color: C.slate6, align: "center", wrap: true, fontFace: "Arial",
    });
  });

  // Who feels this
  slide.addText(`👤  ${c.who_feels_this}`, {
    x: 0.3, y: 4.52, w: 9.4, h: 0.3,
    fontSize: 11, color: C.slate5, italic: true, fontFace: "Arial",
  });
}

function renderSolutionSlide(pptx: PptxInstance, data: Slide) {
  const slide = pptx.addSlide();
  slide.background = { color: C.offwhite };
  addHeaderBand(slide, data.title, data.subtitle, data.slide_number, C.green);
  addFooter(slide);

  const c = data.content as SolutionContent;

  // Solution statement
  roundRect(slide, 0.3, 1.5, 9.4, 0.58, C.greenLight, C.green, 0.08);
  slide.addText(c.solution_statement, {
    x: 0.5, y: 1.55, w: 9.0, h: 0.5,
    fontSize: 14, bold: true, color: C.green, fontFace: "Arial", wrap: true,
  });

  // BEFORE / AFTER columns
  const colY = 2.22;
  const colH = 1.95;
  const colW = 4.35;

  // Before card
  roundRect(slide, 0.3, colY, colW, colH, C.white, C.slate2, 0.1);
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0.3, y: colY, w: colW, h: 0.42,
    fill: { color: "FEE2E2" },
    line: { width: 0 },
  });
  slide.addText("✗  Before", {
    x: 0.42, y: colY + 0.06, w: colW - 0.2, h: 0.3,
    fontSize: 12, bold: true, color: C.red, fontFace: "Arial",
  });
  c.before.forEach((b, i) => {
    slide.addText(`•  ${b}`, {
      x: 0.45, y: colY + 0.52 + i * 0.44, w: colW - 0.25, h: 0.42,
      fontSize: 11, color: C.slate8, wrap: true, fontFace: "Arial",
    });
  });

  // Arrow
  slide.addText("⟶", {
    x: 4.75, y: colY + 0.75, w: 0.5, h: 0.5,
    fontSize: 22, color: C.slate3, align: "center",
  });

  // After card
  roundRect(slide, 5.35, colY, colW, colH, C.white, C.slate2, 0.1);
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 5.35, y: colY, w: colW, h: 0.42,
    fill: { color: C.greenLight },
    line: { width: 0 },
  });
  slide.addText("✓  After", {
    x: 5.47, y: colY + 0.06, w: colW - 0.2, h: 0.3,
    fontSize: 12, bold: true, color: C.green, fontFace: "Arial",
  });
  c.after.forEach((a, i) => {
    slide.addText(`•  ${a}`, {
      x: 5.5, y: colY + 0.52 + i * 0.44, w: colW - 0.25, h: 0.42,
      fontSize: 11, color: C.slate8, wrap: true, fontFace: "Arial",
    });
  });

  // Key differentiator
  roundRect(slide, 0.3, 4.3, 9.4, 0.55, C.ink, undefined, 0.08);
  slide.addText(`⭐  ${c.key_differentiator}`, {
    x: 0.45, y: 4.36, w: 9.1, h: 0.43,
    fontSize: 13, bold: true, color: C.saffron, align: "center", fontFace: "Arial",
  });
}

function renderMarketSizeSlide(pptx: PptxInstance, data: Slide) {
  const slide = pptx.addSlide();
  slide.background = { color: C.offwhite };
  addHeaderBand(slide, data.title, data.subtitle, data.slide_number, C.blue);
  addFooter(slide);

  const c = data.content as MarketSizeContent;

  // Three market boxes with visual weight
  const boxes = [
    { label: "TAM", full: "Total Addressable Market", inr: c.tam_inr, usd: c.tam_usd, bg: C.blue, fg: C.white, accent: C.blueMid, x: 0.3, w: 4.1, h: 2.5 },
    { label: "SAM", full: "Serviceable Market", inr: c.sam_inr, usd: "", bg: C.slate8, fg: C.white, accent: C.slate3, x: 4.55, w: 2.8, h: 2.5 },
    { label: "SOM", full: "Your 3-Year Target", inr: c.som_inr, usd: "", bg: C.white, fg: C.ink, accent: C.blue, x: 7.5, w: 2.2, h: 2.5 },
  ];

  boxes.forEach((box) => {
    roundRect(slide, box.x, 1.52, box.w, box.h, box.bg, box.fg === C.ink ? C.slate2 : undefined, 0.14);
    slide.addText(box.label, {
      x: box.x + 0.18, y: 1.66, w: box.w - 0.36, h: 0.42,
      fontSize: 20, bold: true, color: box.accent, fontFace: "Arial",
    });
    slide.addText(box.full, {
      x: box.x + 0.18, y: 2.1, w: box.w - 0.36, h: 0.3,
      fontSize: 9, color: box.fg, fontFace: "Arial", italic: true,
    });
    slide.addText(box.inr, {
      x: box.x + 0.1, y: 2.42, w: box.w - 0.2, h: 0.9,
      fontSize: box.w > 3 ? 22 : 16, bold: true, color: box.fg, align: "center", wrap: true, fontFace: "Arial",
    });
    if (box.usd) {
      slide.addText(box.usd, {
        x: box.x + 0.1, y: 3.34, w: box.w - 0.2, h: 0.3,
        fontSize: 11, color: box.accent, align: "center", fontFace: "Arial",
      });
    }
  });

  // Growth rate + why now + source strip
  roundRect(slide, 0.3, 4.15, 3.0, 0.72, C.blueLight, C.blue, 0.08);
  slide.addText("📈  CAGR", {
    x: 0.45, y: 4.2, w: 2.7, h: 0.28,
    fontSize: 9, bold: true, color: C.blue, fontFace: "Arial",
  });
  slide.addText(c.growth_rate, {
    x: 0.45, y: 4.48, w: 2.7, h: 0.35,
    fontSize: 18, bold: true, color: C.blue, fontFace: "Arial",
  });

  slide.addText(c.why_now_one_line, {
    x: 3.45, y: 4.2, w: 6.2, h: 0.44,
    fontSize: 11, color: C.slate6, italic: true, wrap: true, fontFace: "Arial",
  });
  slide.addText(`Source: ${c.source}`, {
    x: 3.45, y: 4.68, w: 6.2, h: 0.22,
    fontSize: 8, color: C.slate5, fontFace: "Arial",
  });
}

function renderCustomerSlide(pptx: PptxInstance, data: Slide) {
  const slide = pptx.addSlide();
  slide.background = { color: C.offwhite };
  addHeaderBand(slide, data.title, data.subtitle, data.slide_number, C.saffron);
  addFooter(slide);

  const c = data.content as CustomerContent;

  c.personas.forEach((p, i) => {
    const x = 0.3 + i * 4.85;
    const w = 4.55;
    const cardY = 1.52;
    const cardH = 3.35;

    roundRect(slide, x, cardY, w, cardH, C.white, C.slate2, 0.14);

    // Header band inside card
    slide.addShape("roundRect" as Parameters<typeof slide.addShape>[0], {
      x, y: cardY, w, h: 0.9,
      fill: { color: C.ink },
      line: { width: 0 },
      rectRadius: 0.14,
    });
    // Avatar circle
    slide.addShape("ellipse" as Parameters<typeof slide.addShape>[0], {
      x: x + 0.18, y: cardY + 0.12, w: 0.66, h: 0.66,
      fill: { color: C.saffron },
      line: { width: 0 },
    });
    slide.addText(p.name.charAt(0).toUpperCase(), {
      x: x + 0.18, y: cardY + 0.18, w: 0.66, h: 0.54,
      fontSize: 20, bold: true, color: C.white, align: "center", fontFace: "Arial",
    });
    slide.addText(p.name, {
      x: x + 0.95, y: cardY + 0.1, w: w - 1.1, h: 0.38,
      fontSize: 14, bold: true, color: C.white, fontFace: "Arial",
    });
    slide.addText(p.age_range, {
      x: x + 0.95, y: cardY + 0.5, w: w - 1.1, h: 0.28,
      fontSize: 10, color: C.slate3, fontFace: "Arial",
    });

    // Tier + income badges
    const isTier2or3 = p.tier_city.includes("2") || p.tier_city.includes("3");
    badge(slide, p.tier_city, x + 0.18, cardY + 1.02, 1.5, isTier2or3 ? C.saffron : C.blue, C.white);
    badge(slide, p.income_inr, x + 1.8, cardY + 1.02, w - 2.0, C.greenLight, C.green);

    // Job + frustration
    const rows = [
      { label: "Job to be done", text: p.job_to_be_done, color: C.blue },
      { label: "Biggest frustration", text: p.biggest_frustration, color: C.red },
    ];
    rows.forEach((row, j) => {
      const ry = cardY + 1.45 + j * 0.92;
      slide.addText(row.label.toUpperCase(), {
        x: x + 0.18, y: ry, w: w - 0.36, h: 0.24,
        fontSize: 8, bold: true, color: row.color, fontFace: "Arial",
      });
      slide.addText(row.text, {
        x: x + 0.18, y: ry + 0.24, w: w - 0.36, h: 0.58,
        fontSize: 11, color: C.slate8, wrap: true, fontFace: "Arial",
      });
    });
  });
}

function renderCompetitorSlide(pptx: PptxInstance, data: Slide) {
  const slide = pptx.addSlide();
  slide.background = { color: C.offwhite };
  addHeaderBand(slide, data.title, data.subtitle, data.slide_number, C.blue);
  addFooter(slide);

  const c = data.content as CompetitorContent;

  // Position statement
  roundRect(slide, 0.3, 1.52, 9.4, 0.5, C.blueLight, C.blue, 0.08);
  slide.addText(`💡  ${c.our_position}`, {
    x: 0.45, y: 1.58, w: 9.1, h: 0.38,
    fontSize: 12, bold: true, color: C.blue, fontFace: "Arial", wrap: true,
  });

  // Table
  const tableY = 2.15;
  const colW = [2.3, 2.5, 2.5, 1.4, 0.7];
  const headers = ["Competitor", "Strength", "Weakness", "Threat", "Type"];
  let cx = 0.3;

  // Header row
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0.3, y: tableY, w: 9.4, h: 0.42,
    fill: { color: C.ink },
    line: { width: 0 },
  });
  headers.forEach((h, i) => {
    slide.addText(h, {
      x: cx + 0.08, y: tableY + 0.08, w: colW[i] - 0.1, h: 0.28,
      fontSize: 9, bold: true, color: C.white, fontFace: "Arial",
    });
    cx += colW[i];
  });

  // Data rows
  const threatColors: Record<string, string> = { high: C.red, medium: C.amber, low: C.green };
  c.competitors.forEach((comp, rowIdx) => {
    const rowY = tableY + 0.42 + rowIdx * 0.48;
    const rowBg = rowIdx % 2 === 0 ? C.white : C.card;
    slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
      x: 0.3, y: rowY, w: 9.4, h: 0.46,
      fill: { color: rowBg },
      line: { color: C.slate2, width: 1 },
    });

    let rx = 0.3;
    const cells = [comp.name, comp.their_strength, comp.their_weakness, comp.threat_level.toUpperCase(), comp.threat_level === "high" ? "⚠" : comp.threat_level === "medium" ? "●" : "✓"];
    const cellFg = [C.ink, C.slate6, C.slate6, C.white, C.white];
    const cellBg = ["", "", "", threatColors[comp.threat_level] ?? C.slate5, threatColors[comp.threat_level] ?? C.slate5];
    cells.forEach((cell, ci) => {
      if (cellBg[ci]) {
        slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
          x: rx, y: rowY, w: colW[ci], h: 0.46,
          fill: { color: cellBg[ci] },
          line: { width: 0 },
        });
      }
      slide.addText(cell, {
        x: rx + 0.08, y: rowY + 0.1, w: colW[ci] - 0.1, h: 0.28,
        fontSize: 10, color: cellFg[ci], bold: ci === 0 || ci === 3, fontFace: "Arial",
        align: ci >= 3 ? "center" : "left",
      });
      rx += colW[ci];
    });
  });

  // Advantage banner
  const bannerY = tableY + 0.42 + c.competitors.length * 0.48 + 0.12;
  roundRect(slide, 0.3, bannerY, 9.4, 0.48, C.saffron, undefined, 0.08);
  slide.addText(`🏆  Our Advantage:  ${c.our_advantage}`, {
    x: 0.45, y: bannerY + 0.08, w: 9.1, h: 0.32,
    fontSize: 12, bold: true, color: C.white, fontFace: "Arial",
  });
}

function renderBusinessModelSlide(pptx: PptxInstance, data: Slide) {
  const slide = pptx.addSlide();
  slide.background = { color: C.offwhite };
  addHeaderBand(slide, data.title, data.subtitle, data.slide_number, C.saffron);
  addFooter(slide);

  const c = data.content as BusinessModelContent;
  const n = c.revenue_streams.length;
  const cardW = (9.4 - (n - 1) * 0.25) / n;

  // Revenue stream cards
  c.revenue_streams.forEach((rs, i) => {
    const x = 0.3 + i * (cardW + 0.25);
    roundRect(slide, x, 1.52, cardW, 2.15, C.white, C.slate2, 0.14);

    // Number badge
    slide.addShape("ellipse" as Parameters<typeof slide.addShape>[0], {
      x: x + 0.18, y: 1.66, w: 0.46, h: 0.46,
      fill: { color: C.saffron },
      line: { width: 0 },
    });
    slide.addText(String(i + 1), {
      x: x + 0.18, y: 1.7, w: 0.46, h: 0.38,
      fontSize: 14, bold: true, color: C.white, align: "center", fontFace: "Arial",
    });
    slide.addText(rs.name, {
      x: x + 0.76, y: 1.66, w: cardW - 0.9, h: 0.46,
      fontSize: 13, bold: true, color: C.ink, fontFace: "Arial", wrap: true,
    });
    slide.addText(rs.how_it_works, {
      x: x + 0.18, y: 2.22, w: cardW - 0.36, h: 0.6,
      fontSize: 10, color: C.slate6, wrap: true, fontFace: "Arial",
    });

    // Price highlight
    roundRect(slide, x + 0.18, 2.9, cardW - 0.36, 0.52, C.safLight, C.saffron, 0.08);
    slide.addText(rs.example, {
      x: x + 0.22, y: 2.95, w: cardW - 0.44, h: 0.42,
      fontSize: 16, bold: true, color: C.saffron, fontFace: "Arial", align: "center",
    });
  });

  // Unit economics
  roundRect(slide, 0.3, 3.82, 9.4, 0.62, C.greenLight, C.green, 0.1);
  slide.addText("💰", { x: 0.45, y: 3.88, w: 0.45, h: 0.46, fontSize: 20 });
  slide.addText(c.unit_economics_headline, {
    x: 0.98, y: 3.92, w: 5.0, h: 0.46,
    fontSize: 18, bold: true, color: C.green, fontFace: "Arial",
  });
  slide.addText(c.path_to_profitability, {
    x: 6.1, y: 3.92, w: 3.4, h: 0.46,
    fontSize: 10, color: C.slate6, italic: true, wrap: true, fontFace: "Arial",
    align: "right",
  });
}

function renderGoToMarketSlide(pptx: PptxInstance, data: Slide) {
  const slide = pptx.addSlide();
  slide.background = { color: C.offwhite };
  addHeaderBand(slide, data.title, data.subtitle, data.slide_number, C.green);
  addFooter(slide);

  const c = data.content as GoToMarketContent;
  const colW = 2.95;
  const gap = 0.175;
  const colBgs = [C.ink, C.blue, C.saffron];
  const colFgs = [C.white, C.white, C.white];
  const colAccents = [C.saffron, C.blueMid, C.white];

  c.phases.forEach((phase, i) => {
    const x = 0.3 + i * (colW + gap);
    roundRect(slide, x, 1.52, colW, 3.3, colBgs[i], undefined, 0.12);

    // Phase label
    slide.addText(phase.phase, {
      x: x + 0.18, y: 1.62, w: colW - 0.36, h: 0.3,
      fontSize: 9, bold: true, color: colAccents[i], fontFace: "Arial",
    });
    slide.addText(phase.focus, {
      x: x + 0.18, y: 1.94, w: colW - 0.36, h: 0.55,
      fontSize: 13, bold: true, color: colFgs[i], wrap: true, fontFace: "Arial",
    });

    // Divider
    slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
      x: x + 0.18, y: 2.55, w: colW - 0.36, h: 0.02,
      fill: { color: colAccents[i] + "55" },
      line: { width: 0 },
    });

    phase.key_actions.forEach((action, j) => {
      slide.addText(`→  ${action}`, {
        x: x + 0.18, y: 2.65 + j * 0.42, w: colW - 0.36, h: 0.4,
        fontSize: 10, color: colFgs[i], wrap: true, fontFace: "Arial",
      });
    });

    // Milestone badge
    roundRect(slide, x + 0.18, 4.52, colW - 0.36, 0.18, colAccents[i] + "33", undefined, 0.05);
    slide.addText(`🎯  ${phase.target_milestone}`, {
      x: x + 0.18, y: 4.53, w: colW - 0.36, h: 0.17,
      fontSize: 8, bold: true, color: colAccents[i], align: "center", fontFace: "Arial",
    });
  });

  // First customer channel
  roundRect(slide, 0.3, 4.92, 9.4, 0.38, C.blueLight, C.blue, 0.07);
  slide.addText(`🚀  First channel: ${c.first_customer_channel}`, {
    x: 0.45, y: 4.97, w: 9.1, h: 0.28,
    fontSize: 11, bold: true, color: C.blue, fontFace: "Arial",
  });
}

function renderRiskSlide(pptx: PptxInstance, data: Slide) {
  const slide = pptx.addSlide();
  slide.background = { color: C.offwhite };
  addHeaderBand(slide, data.title, data.subtitle, data.slide_number, C.red);
  addFooter(slide);

  const c = data.content as RiskContent;

  const sevMeta: Record<string, { bg: string; fg: string; label: string }> = {
    high:   { bg: "FEE2E2", fg: C.red,   label: "HIGH" },
    medium: { bg: "FEF3C7", fg: C.amber, label: "MED" },
    low:    { bg: C.greenLight, fg: C.green, label: "LOW" },
  };

  // Risk cards (2x2 grid)
  c.risks.slice(0, 4).forEach((risk, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = 0.3 + col * 4.75;
    const y = 1.52 + row * 1.52;
    const w = 4.55;
    const h = 1.38;
    const meta = sevMeta[risk.severity] ?? sevMeta.medium;

    roundRect(slide, x, y, w, h, C.white, C.slate2, 0.1);
    // Left severity stripe
    slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
      x, y, w: 0.06, h,
      fill: { color: meta.fg },
      line: { width: 0 },
    });
    // Severity pill
    badge(slide, meta.label, x + 0.12, y + 0.1, 0.7, meta.bg, meta.fg);
    // Risk title
    slide.addText(risk.risk, {
      x: x + 0.92, y: y + 0.08, w: w - 1.05, h: 0.38,
      fontSize: 12, bold: true, color: C.ink, wrap: true, fontFace: "Arial",
    });
    // Mitigation
    slide.addText(`💡  ${risk.mitigation}`, {
      x: x + 0.12, y: y + 0.58, w: w - 0.24, h: 0.6,
      fontSize: 10, color: C.slate6, wrap: true, fontFace: "Arial",
    });
  });

  // Honest acknowledgment
  const ackY = 1.52 + Math.ceil(c.risks.length / 2) * 1.52 + 0.04;
  roundRect(slide, 0.3, ackY, 9.4, 0.52, C.blueLight, C.blue, 0.08);
  slide.addText(`🤝  Honest take: ${c.biggest_risk_acknowledged}`, {
    x: 0.45, y: ackY + 0.1, w: 9.1, h: 0.35,
    fontSize: 11, color: C.blue, italic: true, wrap: true, fontFace: "Arial",
  });
}

function renderWhyNowSlide(pptx: PptxInstance, data: Slide) {
  const slide = pptx.addSlide();
  slide.background = { color: C.offwhite };
  addHeaderBand(slide, data.title, data.subtitle, data.slide_number, C.saffron);
  addFooter(slide);

  const c = data.content as WhyNowContent;

  const cardColors = [
    { bg: C.ink, accent: C.saffron, fg: C.white, muted: C.slate3 },
    { bg: C.blue, accent: C.blueMid, fg: C.white, muted: C.blueMid },
    { bg: C.saffron, accent: C.white, fg: C.white, muted: "FFFFFF88" },
  ];

  const colW = 2.95;
  const gap = 0.175;
  c.tailwinds.forEach((tw, i) => {
    const x = 0.3 + i * (colW + gap);
    const cc = cardColors[i];
    roundRect(slide, x, 1.52, colW, 2.7, cc.bg, undefined, 0.14);

    // Number
    slide.addText(["01", "02", "03"][i], {
      x: x + 0.18, y: 1.62, w: 0.55, h: 0.48,
      fontSize: 24, bold: true, color: cc.accent, fontFace: "Arial",
    });
    slide.addText(tw.trend, {
      x: x + 0.18, y: 2.14, w: colW - 0.36, h: 0.55,
      fontSize: 14, bold: true, color: cc.fg, wrap: true, fontFace: "Arial",
    });
    slide.addText(tw.evidence, {
      x: x + 0.18, y: 2.72, w: colW - 0.36, h: 0.55,
      fontSize: 10, color: cc.accent, italic: true, wrap: true, fontFace: "Arial",
    });
    slide.addText(tw.impact_on_us, {
      x: x + 0.18, y: 3.3, w: colW - 0.36, h: 0.7,
      fontSize: 11, bold: true, color: cc.fg, wrap: true, fontFace: "Arial",
    });
  });

  // Inflection point
  roundRect(slide, 0.3, 4.38, 9.4, 0.58, C.ink, undefined, 0.1);
  slide.addText(`⚡  ${c.inflection_point}`, {
    x: 0.45, y: 4.46, w: 9.1, h: 0.42,
    fontSize: 14, bold: true, color: C.saffron, align: "center", fontFace: "Arial",
  });
}

function renderAskSlide(pptx: PptxInstance, data: Slide) {
  const slide = pptx.addSlide();
  slide.background = { color: C.ink };
  addFooter(slide);

  const c = data.content as AskContent;

  // Full dark header
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0, y: 0, w: 10, h: 1.35,
    fill: { color: C.ink },
    line: { width: 0 },
  });
  slide.addShape("rect" as Parameters<typeof slide.addShape>[0], {
    x: 0, y: 1.3, w: 10, h: 0.07,
    fill: { color: C.saffron },
    line: { width: 0 },
  });
  slide.addText(data.title, {
    x: 0.35, y: 0.12, w: 8.5, h: 0.58,
    fontSize: 26, bold: true, color: C.white, fontFace: "Arial",
  });
  if (data.subtitle) {
    slide.addText(data.subtitle, {
      x: 0.35, y: 0.72, w: 8.5, h: 0.32,
      fontSize: 12, color: C.saffron, fontFace: "Arial", italic: true,
    });
  }
  // Slide number
  badge(slide, "10", 9.0, 0.15, 0.7, C.saffron, C.white);

  if (c.mode === "funding_ask" && c.amount_inr) {
    // Big amount
    slide.addText(c.amount_inr, {
      x: 0.3, y: 1.52, w: 9.4, h: 1.1,
      fontSize: 52, bold: true, color: C.saffron, align: "center", fontFace: "Arial",
    });
    // Runway
    if (c.runway_months) {
      badge(slide, `${c.runway_months} months runway`, 3.5, 2.7, 3.0, C.green + "33", C.green);
    }
    // Use of funds
    const dotColors = [C.saffron, C.blue, C.green, "A78BFA"];
    (c.use_of_funds ?? []).forEach((use, i) => {
      const fy = 3.1 + i * 0.45;
      slide.addShape("ellipse" as Parameters<typeof slide.addShape>[0], {
        x: 0.55, y: fy + 0.1, w: 0.2, h: 0.2,
        fill: { color: dotColors[i % dotColors.length] },
        line: { width: 0 },
      });
      slide.addText(use, {
        x: 0.88, y: fy, w: 8.6, h: 0.4,
        fontSize: 13, color: C.white, fontFace: "Arial",
      });
    });
  } else {
    (c.next_steps ?? []).slice(0, 4).forEach((step, i) => {
      const col = i % 2;
      const row = Math.floor(i / 2);
      const x = 0.3 + col * 4.9;
      const y = 1.52 + row * 1.3;
      roundRect(slide, x, y, 4.6, 1.18, C.slate8, C.slate5, 0.12);
      slide.addText(String(i + 1), {
        x: x + 0.18, y: y + 0.12, w: 0.55, h: 0.7,
        fontSize: 30, bold: true, color: C.saffron, fontFace: "Arial",
      });
      slide.addText(step, {
        x: x + 0.82, y: y + 0.22, w: 3.62, h: 0.75,
        fontSize: 12, color: C.white, wrap: true, fontFace: "Arial",
      });
    });
  }

  // Contact + closing
  slide.addText(c.contact_prompt, {
    x: 0.3, y: 4.55, w: 9.4, h: 0.38,
    fontSize: 15, bold: true, color: C.white, align: "center", fontFace: "Arial",
  });
  slide.addText(c.closing_statement, {
    x: 0.3, y: 4.95, w: 9.4, h: 0.3,
    fontSize: 11, color: C.saffron, italic: true, align: "center", fontFace: "Arial",
  });
}

// ── MAIN EXPORT ────────────────────────────────────────────────────────────────

export async function generatePPTX(deckData: PitchDeckOutput): Promise<Blob> {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";

  // Cover slide
  const cover = pptx.addSlide();
  cover.background = { color: C.ink };
  cover.addShape("rect" as Parameters<typeof cover.addShape>[0], {
    x: 0, y: 3.8, w: 10, h: 1.85,
    fill: { color: C.saffron },
    line: { width: 0 },
  });
  cover.addShape("ellipse" as Parameters<typeof cover.addShape>[0], {
    x: 6.5, y: -1.0, w: 5.5, h: 5.5,
    fill: { color: C.slate8 },
    line: { width: 0 },
  });
  cover.addText("MarketMind AI", {
    x: 0.5, y: 0.5, w: 5.5, h: 0.5,
    fontSize: 13, color: C.saffron, bold: true, fontFace: "Arial",
  });
  cover.addText(deckData.deck_title, {
    x: 0.5, y: 1.1, w: 7.5, h: 1.4,
    fontSize: 36, bold: true, color: C.white, fontFace: "Arial", wrap: true,
  });
  cover.addText(deckData.tagline, {
    x: 0.5, y: 2.6, w: 7.0, h: 0.55,
    fontSize: 16, color: C.slate3, fontFace: "Arial", italic: true,
  });
  cover.addText(deckData.idea_name, {
    x: 0.5, y: 3.92, w: 5.0, h: 0.42,
    fontSize: 20, bold: true, color: C.white, fontFace: "Arial",
  });
  cover.addText(new Date(deckData.generated_at).toLocaleDateString("en-IN", { year: "numeric", month: "long" }), {
    x: 0.5, y: 4.38, w: 5.0, h: 0.32,
    fontSize: 11, color: C.white, fontFace: "Arial",
  });
  cover.addText("Confidential — For Investor Discussion Only", {
    x: 0.5, y: 5.1, w: 9.0, h: 0.25,
    fontSize: 8, color: C.white + "99", fontFace: "Arial",
  });

  const renderers: Record<string, (pptx: PptxInstance, slide: Slide) => void> = {
    problem:        renderProblemSlide,
    solution:       renderSolutionSlide,
    market_size:    renderMarketSizeSlide,
    customer:       renderCustomerSlide,
    competitor:     renderCompetitorSlide,
    business_model: renderBusinessModelSlide,
    go_to_market:   renderGoToMarketSlide,
    risk:           renderRiskSlide,
    why_now:        renderWhyNowSlide,
    ask:            renderAskSlide,
  };

  for (const slide of deckData.slides) {
    const renderer = renderers[slide.slide_type];
    if (renderer) renderer(pptx, slide);
  }

  const blob = await pptx.write({ outputType: "blob" }) as unknown as Blob;
  return blob;
}
